import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useEffect, useState} from "react";

export default function Home() {
    const [input, setInput] = useState("");
    const [output, setOutput] = useState("");

    const handleInputChange = (e) => {
        setInput(e.currentTarget.value);
    };


    function rainbowify(text) {
        let min = 0
        let max = 4
        let count = Math.floor(Math.random() * (max - min) + min)
        let output = "";

        for (let i in text) {
            if (text[i] == " ") continue

            if (count == 0) {
                output = output + "<enemy>" + text[i] + "</>"
                count += 1
                continue
            }
            if (count == 1) {
                output = output + "<system>" + text[i] + "</>"
                count += 1
                continue
            }
            if (count == 2) {
                output = output + "<notification>" + text[i] + "</>"
                count += 1
                continue
            }
            if (count == 3) {
                output = output + "<team>" + text[i] + "</>"
                count += 1
                continue
            }
            if (count == 4) {
                output = output + "<warning>" + text[i] + "</>"
                count = 0
                continue
            }
        }
        console.log(output)
        setOutput(output)
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to my Valorant text editor!
        </h1>

          <div>
              <h2>
                  Input Text
              </h2>
              <input className={"input"} onChange={handleInputChange} value={input}/>
              <button onClick={() => {
                  rainbowify(input)
              }}>Rainbowify!</button>
          </div>
          <code>{output}</code>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
